### ISSUE TITLE
bitcask/src/bitcask_merge_delete.erl:46: Warning: type queue/0 is deprecated and will be removed in OTP 18.0;  [JIRA: RIAK-1550]

### ISSUE THREAD

**Issue by netroby** [basho/bitcask#203]
/vagrant/workspace/erlang/bertie/deps/bitcask/src/bitcask_merge_delete.erl:46: Warning: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1

**Comment by tnt-dev** [comment]
Maybe we can use OTP version detection?

rebar.config 
```
{erl_opts, [
{platform_define, "^[0-9]+", namespaced_queues},
...]}.
````
(Erlang releases after 17 don't put R in front of their name)

bitcask_merge_delete.erl
```
...
-ifdef(namespaced_queues).
-type bitacask_queue() :: queue:queue().
-else.
-type bitacask_queue() :: queue().
-endif.

-record(state, {q :: bitcask_queue()}).
...
```

**Comment by Basho-JIRA** [comment]
Please review and assign based on your findings. 

***[posted via JIRA by Derek Somogyi]***

**Comment by Basho-JIRA** [comment]
This has been fixed in the work done to update Bitcask to support OTP 17. 

***[posted via JIRA by Sean Cribbs]***
