### ISSUE TITLE
rebar abort [JIRA: RIAK-2485]

### ISSUE THREAD

**Issue by dendisuhubdy** [basho/bitcask#237]
C02QH2D7G8WM:bitcask userone$ make
./rebar compile skip_deps=true
==> bitcask (compile)
Dependency not available: meck-0.8.2 ({git,"git://github.com/basho/meck.git",
                                       {tag,"0.8.2"}})
Dependency not available: cuttlefish-.\* ({git,
                                          "git://github.com/basho/cuttlefish.git",
                                          {tag,"2.0.5"}})
ERROR: compile failed while processing /Users/userone/Documents/workspace/bitcask: rebar_abort
make: **\* [compile-no-deps] Error 1

**Comment by jsvisa** [comment]
@dendisuhubdy Seems you don't fetch the dependences before compile, try it below:
```
make all
```

**Comment by yati-sagade** [comment]
Same error here, `make all` did not fix it (the step did fetch all dependencies, but fails trying to build cuttlefish). Any ideas?

**Comment by yati-sagade** [comment]
FWIW, on Ubuntu, `sudo apt install erlang-dev erlang-eunit` fixed it for me.

**Comment by dendisuhubdy** [comment]
@jsvisa lemme try it

**Comment by ghost** [comment]
You may find the packages at https://packagecloud.io/erlang-solutions/riak of use - personally I tend to avoid using the split up distro packages to build Riak stuff. If that doesn't suit your needs and you find you want to run multiple erlang versions on your development system - you may like to use https://github.com/asdf-vm/asdf instead (will require installing the development dependencies first)
