### ISSUE TITLE
Recreate hintfile

### ISSUE THREAD

**Issue by Konstantin74R** [basho/bitcask#273]
Hi,
Hitfiles was dropped and riak starts very long time. My question: How can I recreate hintfiles?
Addition: How recalculate CRC in data files for all key in them? In my errors 
{riak_kv_bitcask_backend,key_transform_to_1,[<<>>]   and i don't know how determinate which vnode/key have not correctly CRC.

Riak 2.1.1

**Comment by Bob-The-Marauder** [comment]
Bitcask hintfiles are automatically generated by Bitcask. If you have a lot of data and all hintfiles have been deleted then the initial start up may be a little slower than normal but as Riak is usually kept running 24/7, that should not be a problem.
Riak will function perfectly well without hint files and generate them on the fly as needed. If you have corrupt hintfile errors, delete the corrupt hintfiles and Riak will rebuild them.

**Comment by Konstantin74R** [comment]
Thank you!
